package ejercicio4;

public class Art {

    public void print_pokemon(String n_pokemon) {
        switch (n_pokemon) {
            case "bulbasur":
                System.out.printf("                                           /\n");
                System.out.printf("                        _,.------....___,.' ',.-.\n");
                System.out.printf("                     ,-'          _,.--\"        |\n");
                System.out.printf("                   ,'         _.-'              .\n");
                System.out.printf("                  /   ,     ,'                   `\n");
                System.out.printf("                 .   /     /                     ``.\n");
                System.out.printf("                 |  |     .                       \\.\\\n");
                System.out.printf("       ____      |___._.  |       __               \\ `.\n");
                System.out.printf("     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\\n");
                System.out.printf("    .  ,            __               `              |   .\n");
                System.out.printf("    `,'         ,-\"'  .               \\             |    L\n");
                System.out.printf("   ,'          '    _.'                -._          /    |\n");
                System.out.printf("  ,`-.    ,\".   `--'                      >.      ,'     |\n");
                System.out.printf(" . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'\n");
                System.out.printf(" ||:, .           ,'  ;  /  / \\ `        `.    .      .'/\n");
                System.out.printf(" j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /\n");
                System.out.printf("/ L:_  |                 .  \"' :_;                `.'.'\n");
                System.out.printf(".    \"\"'                  \"\"\"\"\"'                    V\n");
                System.out.printf(" `.                                 .    `.   _,..  `\n");
                System.out.printf("   `,_   .    .                _,-'/    .. `,'   __  `\n");
                System.out.printf("    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .\n");
                System.out.printf("   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |\n");
                System.out.printf("  .   _  `\"\"'--.._____..--\"   ,             '         |\n");
                System.out.printf("  | .\" `. `-.                /-.           /          ,\n");
                System.out.printf("  | `._.'    `,_            ;  /         ,'          .\n");
                System.out.printf(" .'          /| `-.        . ,'         ,           ,\n");
                System.out.printf(" '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'\n");
                System.out.printf(" `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' mh\n");
                System.out.printf("\n");
                System.out.printf("\n");

                break;

            case "charmander":
                System.out.printf("              _.--\"\"`-..\n");
                System.out.printf("            ,'          `.\n");
                System.out.printf("          ,'          __  `.\n");
                System.out.printf("         /|          \" __   \\\n");
                System.out.printf("        , |           / |.   .\n");
                System.out.printf("        |,'          !_.'|   |\n");
                System.out.printf("      ,'             '   |   |\n");
                System.out.printf("     /              |`--'|   |\n");
                System.out.printf("    |                `---'   |\n");
                System.out.printf("     .   ,                   |                       ,\".\n");
                System.out.printf("      ._     '           _'  |                    , ' \\ `\n");
                System.out.printf("  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|\n");
                System.out.printf("  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\\n");
                System.out.printf("-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .\n");
                System.out.printf("  `,         \"\"\"\"'     `.              ,'         |   |  ',,\n");
                System.out.printf("    `.      '            '            /          '    |'. |/\n");
                System.out.printf("      `.   |              \\       _,-'           |       ''\n");
                System.out.printf("        `._'               \\   '\"\\                .      |\n");
                System.out.printf("           |                '     \\                `._  ,'\n");
                System.out.printf("           |                 '     \\                 .'|\n");
                System.out.printf("           |                 .      \\                | |\n");
                System.out.printf("           |                 |       L              ,' |\n");
                System.out.printf("           `                 |       |             /   '\n");
                System.out.printf("            \\                |       |           ,'   /\n");
                System.out.printf("          ,' \\               |  _.._ ,-..___,..-'    ,'\n");
                System.out.printf("         /     .             .      `!             ,j'\n");
                System.out.printf("        /       `.          /        .           .'/\n");
                System.out.printf("       .          `.       /         |        _.'.'\n");
                System.out.printf("        `.          7`'---'          |------\"'_.'\n");
                System.out.printf("       _,.`,_     _'                ,''-----\"'\n");
                System.out.printf("   _,-_    '       `.     .'      ,\\\n");
                System.out.printf("   -\" /`.         _,'     | _  _  _.|\n");
                System.out.printf("    \"\"--'---\"\"\"\"\"'        `' '! |! /\n");
                System.out.printf("                            `\" \" -' mh\n");
                System.out.printf("\n");
                System.out.printf("\n");

                break;

            case "squirtle":
                System.out.printf("               _,........__\n");
                System.out.printf("            ,-'            \"`-.\n");
                System.out.printf("          ,'                   `-.\n");
                System.out.printf("        ,'                        \\\n");
                System.out.printf("      ,'                           .\n");
                System.out.printf("      .'\\               ,\"\".       `\n");
                System.out.printf("     ._.'|             / |  `       \\\n");
                System.out.printf("     |   |            `-.'  ||       `.\n");
                System.out.printf("     |   |            '-._,'||       | \\\n");
                System.out.printf("     .`.,'             `..,'.'       , |`-.\n");
                System.out.printf("     l                       .'`.  _/  |   `.\n");
                System.out.printf("     `-.._'-   ,          _ _'   -\" \\  .     `\n");
                System.out.printf("`.\"\"\"\"\"'-.`-...,---------','         `. `....__.\n");
                System.out.printf(".'        `\"-..___      __,'\\          \\  \\     \\\n");
                System.out.printf("\\_ .          |   `\"\"\"\"'    `.           . \\     \\\n");
                System.out.printf("  `.          |              `.          |  .     L\n");
                System.out.printf("    `.        |`--...________.'.        j   |     |\n");
                System.out.printf("      `._    .'      |          `.     .|   ,     |\n");
                System.out.printf("         `--,\\       .            `7\"\"' |  ,      |\n");
                System.out.printf("            ` `      `            /     |  |      |    _,-'\"\"\"`-.\n");
                System.out.printf("             \\ `.     .          /      |  '      |  ,'          `.\n");
                System.out.printf("              \\  v.__  .        '       .   \\    /| /              \\\n");
                System.out.printf("               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |\n");
                System.out.printf("                `        .        `._ ___,j.  `/ .-       ,---.     |\n");
                System.out.printf("                ,`-.      \\         .\"     `.  |/        j     `    |\n");
                System.out.printf("               /    `.     \\       /         \\ /         |     /    j\n");
                System.out.printf("              |       `-.   7-.._ .          |\"          '         /\n");
                System.out.printf("              |          `./_    `|          |            .     _,'\n");
                System.out.printf("              `.           / `----|          |-............`---'\n");
                System.out.printf("                \\          \\      |          |\n");
                System.out.printf("               ,'           )     `.         |\n");
                System.out.printf("                7____,,..--'      /          |\n");
                System.out.printf("                                  `---.__,--.'mh\n");

                break;

            case "pikachu":
                System.out.printf("                                             ,-.\n");
                System.out.printf("                                          _.|  '\n");
                System.out.printf("                                        .'  | /\n");
                System.out.printf("                                      ,'    |'\n");
                System.out.printf("                                     /      /\n");
                System.out.printf("                       _..----\"\"---.'      /\n");
                System.out.printf(" _.....---------...,-\"\"                  ,'\n");
                System.out.printf(" `-._  \\                                /\n");
                System.out.printf("     `-.+_            __           ,--. .\n");
                System.out.printf("          `-.._     .:  ).        (`--\"| \\\n");
                System.out.printf("               7    | `\" |         `...'  \\\n");
                System.out.printf("               |     `--'     '+\"        ,\". ,\"\"-\n");
                System.out.printf("               |   _...        .____     | |/    '\n");
                System.out.printf("          _.   |  .    `.  '--\"   /      `./     j\n");
                System.out.printf("         \\' `-.|  '     |   `.   /        /     /\n");
                System.out.printf("         '     `-. `---\"      `-\"        /     /\n");
                System.out.printf("          \\       `.                  _,'     /\n");
                System.out.printf("           \\        `                        .\n");
                System.out.printf("            \\                                j\n");
                System.out.printf("             \\                              /\n");
                System.out.printf("              `.                           .\n");
                System.out.printf("                +                          \\\n");
                System.out.printf("                |                           L\n");
                System.out.printf("                |                           |\n");
                System.out.printf("                |  _ /,                     |\n");
                System.out.printf("                | | L)'..                   |\n");
                System.out.printf("                | .    | `                  |\n");
                System.out.printf("                '  \\'   L                   '\n");
                System.out.printf("                 \\  \\   |                  j\n");
                System.out.printf("                  `. `__'                 /\n");
                System.out.printf("                _,.--.---........__      /\n");
                System.out.printf("               ---.,'---`         |   -j\"\n");
                System.out.printf("                .-'  '....__      L    |\n");
                System.out.printf("              \"\"--..    _,-'       \\ l||\n");
                System.out.printf("                  ,-'  .....------. `||'\n");
                System.out.printf("               _,'                /\n");
                System.out.printf("             ,'                  /\n");
                System.out.printf("            '---------+-        /\n");
                System.out.printf("                     /         /\n");
                System.out.printf("                   .'         /\n");
                System.out.printf("                 .'          /\n");
                System.out.printf("               ,'           /\n");
                System.out.printf("             _'....----\"\"\"\"\" mh\n");

                break;
            case "vs":
                System.out.println(" █████   █████  █████████ ");
                System.out.println("░░███   ░░███  ███░░░░░███");
                System.out.println(" ░███    ░███ ░███    ░░░ ");
                System.out.println(" ░███    ░███ ░░█████████ ");
                System.out.println(" ░░███   ███   ░░░░░░░░███ ");
                System.out.println("  ░░░█████░    ███    ░███ ");
                System.out.println("    ░░███     ░░█████████ ");
                System.out.println("     ░░░       ░░░░░░░░░  ");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                System.out.println("");
                break;

            case "ivysour":
                System.out.printf("                               ,'\"`.,./.\n");
                System.out.printf("                             ,'        Y',\"..\n");
                System.out.printf("                           ,'           \\  | \\\n");
                System.out.printf("                          /              . |  `\n");
                System.out.printf("                         /               | |   \\\n");
                System.out.printf("            __          .                | |    .\n");
                System.out.printf("       _   \\  `. ---.   |                | j    |\n");
                System.out.printf("      / `-._\\   `Y   \\  |                |.     |\n");
                System.out.printf("     _`.    ``    \\   \\ |..              '      |,-'\"\"7,....\n");
                System.out.printf("     l     '-.     . , `|  | , |`. , ,  /,     ,'    '/   ,'_,.-.\n");
                System.out.printf("     `-..     `-.  : :     |/ `   ' \"\\,' | _  /          '-'    /___\n");
                System.out.printf("      \\\"\"' __.,.-`.: :        /   /._    l'.,'\n");
                System.out.printf("       `--,   _.-' `\".           /__ `'-.' '         .\n");
                System.out.printf("       ,---..._,.--\"\"\"\"\"\"\"--.__..----,-.'   .  /    .'   ,.--\n");
                System.out.printf("       |                          ,':| /    | /     ;.,-'--      ,.-\n");
                System.out.printf("       |     .---.              .'  :|'     |/ ,.-='\"-.`\"`' _   -.'\n");
                System.out.printf("       /    \\    /               `. :|--.  _L,\"---.._        \"----'\n");
                System.out.printf("     ,' `.   \\ ,'           _,     `''   ``.-'       `-  -..___,'\n");
                System.out.printf("    . ,.  .   `   __     .-'  _.-           `.     .__    \\\n");
                System.out.printf("    |. |`        \"  ;   !   ,.  |             `.    `.`'---'\n");
                System.out.printf("    ,| |C\\       ` /    | ,' |(]|            -. |-..--`\n");
                System.out.printf("   /  \"'--'       '      /___|__]        `.  `- |`.\n");
                System.out.printf("  .       ,'                   ,   /       .    `. \\\n");
                System.out.printf("    \\                      .,-'  ,'         .     `-.\n");
                System.out.printf("     x---..`.  -'  __..--'\"/\"\"\"\"\"  ,-.      |   |   |\n");
                System.out.printf("    / \\--._'-.,.--'     _`-    _. ' /       |     -.|\n");
                System.out.printf("   ,   .   `-..__ ...--'  _,.-' | `   ,.-.  ;   /  '|\n");
                System.out.printf("  .  _,'         '\"-----\"\"      |    `   | /  ,'    ;\n");
                System.out.printf("  |-'  .-.    `._               |     `._// ,'     /\n");
                System.out.printf(" _|    `-'   _,' \"`--.._________|        `,'    _ /.\n");
                System.out.printf("//\\   ,-._.'\"/\\__,.   _,\"     /_\\__/`. /'.-.'.-/_,`-' mh\n");
                System.out.printf("`-\"`\"' v'    `\"  `-`-\"              `-'`-`  `'\n");

                break;

            case "venusaur":
                System.out.print("                           _._       _,._\n");
                System.out.print("                        _.'   `. ' .'   _`.\n");
                System.out.print("                ,\"\"\"/`\"\"-.-.,/. ` V'\\-,`.,--/\"\"\".\"-..\n");
                System.out.print("              ,'    `...,' . ,\\-----._|     `.   /   \\\n");
                System.out.print("             `.            .`  -'`\"\" .._   :> `-'   `.\n");
                System.out.print("            ,'  ,-.  _,.-'| `..___ ,'   |'-..__   .._ L\n");
                System.out.print("           .    \\_ -'   `-'     ..      `.-' `.`-.'_ .|\n");
                System.out.print("           |   ,',-,--..  ,--../  `.  .-.    , `-.  ``.\n");
                System.out.print("           `.,' ,  |   |  `.  /'/,,.\\/  |    \\|   |\n");
                System.out.print("                `  `---'    `j   .   \\  .     '   j\n");
                System.out.print("              ,__`\"        ,'|`'\\_/`.'\\'        |\\-'-, _,.\n");
                System.out.print("       .--...`-. `-`. /    '- ..      _,    /\\ ,' .--\"'  ,'\".\n");
                System.out.print("     _'-\"\"-    --  _`'-.../ __ '.'`-^,_`-\"\"\"\"---....__  ' _,-`\n");
                System.out.print("   _.----`  _..--.'        |  \"`-..-\" __|'\"'         .\"\"-. \"\"'--.._\n");
                System.out.print("  /        '    /     ,  _.+-.'  ||._'   \"\"\"\". .          `     .__\\\n");
                System.out.print(" `---    /        /  / j'       _/|..`  -. `-`\\ \\   \\  \\   `.  \\ `-..\n");
                System.out.print(",\" _.-' /    /` ./  /`_|_,-\"   ','|       `. | -'`._,   L  \\ .  `.   |\n");
                System.out.print("`\"' /  /  / ,__...-----| _.,  ,'            `|----.._`-.|' |. .` ..  .\n");
                System.out.print("   /  '| /.,/   \\--.._ `-,' ,          .  '`.'  __,., '  ''``._ \\ \\`,'\n");
                System.out.print("  /_,'---  ,     \\`._,-` \\ //  / . \\    `._,  -`,  / / _   |   `-L -\n");
                System.out.print("   /       `.     ,  ..._ ' `_/ '| |\\ `._'       '-.'   `.,'     |\n");
                System.out.print("  '         /    /  ..   `.  `./ | ; `.'    ,\"\" ,.  `.    \\      |\n");
                System.out.print("   `.     ,'   ,'   | |\\  |       \"        |  ,'\\ |   \\    `    ,L\n");
                System.out.print("   /|`.  /    '     | `-| '                  /`-' |    L    `._/  \\\n");
                System.out.print("  / | .`|    |  .   `._.'                   `.__,'   .  |     |  (`\n");
                System.out.print(" '-\"\"-'_|    `. `.__,._____     .    _,        ____ ,-  j     \".-'\"'\n");
                System.out.print("        \\      `-.  \\/.    `\"--.._    _,.---'\"\"\\/  \"_,.'     /-'\n");
                System.out.print("         )        `-._ '-.        `--\"      _.-'.-\"\"        `.\n");
                System.out.print("        ./            `,. `\".._________...\"\"_.-\"`.          _j\n");
                System.out.print("       /_\\.__,\"\".   ,.'  \"`-...________.---\"     .\".   ,.  / \\\n");
                System.out.print("              \\_/\"\"\"-'                           `-'--(_,`\"`-` mh\n");

                break;

            case "charmeleon":
                System.out.print("                      ,-'`\\\n");
                System.out.print("                  _,\"'    j\n");
                System.out.print("           __....+       /               .\n");
                System.out.print("       ,-'\"             /               ; `-._.'.\n");
                System.out.print("      /                (              ,'       .'\n");
                System.out.print("     |            _.    \\             \\   ---._ `-.\n");
                System.out.print("     ,|    ,   _.'  Y    \\             `- ,'   \\   `.`.\n");
                System.out.print("     l'    \\ ,'._,\\ `.    .              /       ,--. l\n");
                System.out.print("  .,-        `._  |  |    |              \\       _   l .\n");
                System.out.print(" /              `\"--'    /              .'       ``. |  )\n");
                System.out.print(".\\    ,                 |                .        \\ `. '\n");
                System.out.print("`.                .     |                '._  __   ;. \\'\n");
                System.out.print("  `-..--------...'       \\                  `'  `-\"'.  \\\n");
                System.out.print("      `......___          `._                        |  \\\n");
                System.out.print("               /`            `..                     |   .\n");
                System.out.print("              /|                `-.                  |    L\n");
                System.out.print("             / |               \\   `._               .    |\n");
                System.out.print("           ,'  |,-\"-.   .       .     `.            /     |\n");
                System.out.print("         ,'    |     '   \\      |       `.         /      |\n");
                System.out.print("       ,'     /|       \\  .     |         .       /       |\n");
                System.out.print("     ,'      / |        \\  .    +          \\    ,'       .'\n");
                System.out.print("    .       .  |         \\ |     \\          \\_,'        / j\n");
                System.out.print("    |       |  L          `|      .          `        ,' '\n");
                System.out.print("    |    _. |   \\          /      |           .     .' ,'\n");
                System.out.print("    |   /  `|    \\        .       |  /        |   ,' .'\n");
                System.out.print("    |   ,-..\\     -.     ,        | /         |,.' ,'\n");
                System.out.print("    `. |___,`    /  `.   /`.       '          |  .'\n");
                System.out.print("      '-`-'     j     ` /.\"7-..../|          ,`-'\n");
                System.out.print("                |        .'  / _/_|          .\n");
                System.out.print("                `,       `\"'/\"'    \\          `.\n");
                System.out.print("                  `,       '.       `.         |\n");
                System.out.print("             __,.-'         `.        \\'       |\n");
                System.out.print("            /_,-'\\          ,'        |        _.\n");
                System.out.print("             |___.---.   ,-'        .-':,-\"`\\,' .\n");
                System.out.print("                  L,.--\"'           '-' |  ,' `-.\\\n");
                System.out.print("                                        `.' mh\n");

                break;

            case "charizard":
                System.out.print("                 .\"-,.__\n");
                System.out.print("                 `.     `.  ,\n");
                System.out.print("              .--'  .._,'\"-' `.\n");
                System.out.print("             .    .'         `'\n");
                System.out.print("             `.   /          ,'\n");
                System.out.print("               `  '--.   ,-\"'\n");
                System.out.print("                `\"`   |  \\\n");
                System.out.print("                   -. \\, |\n");
                System.out.print("                    `--Y.'      ___.\n");
                System.out.print("                         \\     L._, \\\n");
                System.out.print("               _.,        `.   <  <\\                _\n");
                System.out.print("             ,' '           `, `.   | \\            ( `\n");
                System.out.print("          ../, `.            `  |    .\\`.           \\ \\_\n");
                System.out.print("         ,' ,..  .           _.,'    ||\\l            )  '\".\n");
                System.out.print("        , ,'   \\           ,'.-.`-._,'  |           .  _._`.\n");
                System.out.print("      ,' /      \\ \\        `' ' `--/   | \\          / /   ..\\\n");
                System.out.print("    .'  /        \\ .         |\\__ - _ ,'` `        / /     `.`.\n");
                System.out.print("    |  '          ..         `-...-\"  |  `-'      / /        . `.\n");
                System.out.print("    | /           |L__           |    |          / /          `. `.\n");
                System.out.print("   , /            .   .          |    |         / /             ` `\n");
                System.out.print("  / /          ,. ,`._ `-_       |    |  _   ,-' /               ` \\\n");
                System.out.print(" / .           \\\"`_/. `-_ \\_,.  ,'    +-' `-'  _,        ..,-.    \\`.\n");
                System.out.print(".  '         .-f    ,'   `    '.       \\__.---'     _   .'   '     \\ \\\n");
                System.out.print("' /          `.'    l     .' /          \\..      ,_|/   `.  ,'`     L`\n");
                System.out.print("|'      _.-\"\"` `.    \\ _,'  `            \\ `.___`.'\"`-.  , |   |    | \\\n");
                System.out.print("||    ,'      `. `.   '       _,...._        `  |    `/ '  |   '     .|\n");
                System.out.print("||  ,'          `. ;.,.---' ,'       `.   `.. `-'  .-' /_ .'    ;_   ||\n");
                System.out.print("|| '              V      / /           `   | `   ,'   ,' '.    !  `. ||\n");
                System.out.print("||/            _,-------7 '              . |  `-'    l         /    `||\n");
                System.out.print(". |          ,' .-   ,' ||               | .-.        `.      .'     ||\n");
                System.out.print(" `'        ,'    `\".'    |               |    `.        '. -.'       `'\n");
                System.out.print("          /      ,'      |               |,'    \\-.._,.'/'\n");
                System.out.print("          .     /        .               .       \\    .''\n");
                System.out.print("        .`.    |         `.             /         :_,'.'\n");
                System.out.print("          \\ `...\\   _     ,'-.        .'         /_.-'\n");
                System.out.print("           `-.__ `,  `'   .  _.>----''.  _  __  /\n");
                System.out.print("                .'        /\"'          |  \"'   '_\n");
                System.out.print("               /_|.-'\\ ,\".             '.'`__'-( \\\n");
                System.out.print("                 / ,\"'\"\\,'               `/  `-.|\" mh\n");

                break;

            case "wartortle":
                System.out.print("     __                                _.--'\"7\n");
                System.out.print("    `. `--._                        ,-'_,-  ,'\n");
                System.out.print("     ,'  `-.`-.                   /' .'    ,|\n");
                System.out.print("     `.     `. `-     __...___   /  /     - j\n");
                System.out.print("       `.     `  `.-\"\"        \" .  /       /\n");
                System.out.print("         \\     /                ` /       /\n");
                System.out.print("          \\   /                         ,'\n");
                System.out.print("          '._'_               ,-'       |\n");
                System.out.print("             | \\            ,|  |   ...-'\n");
                System.out.print("             || `         ,|_|  |   | `             _..__\n");
                System.out.print("            /|| |          | |  |   |  \\  _,_    .-\"     `-.\n");
                System.out.print("           | '.-'          |_|_,' __!  | /|  |  /           \\\n");
                System.out.print("   ,-...___ .=                  ._..'  /`.| ,`,.      _,.._ |\n");
                System.out.print("  |   |,.. \\     '  `'        ____,  ,' `--','  |    /      |\n");
                System.out.print(" ,`-..'  _)  .`-..___,---'_...._/  .'      '-...'   |      /\n");
                System.out.print("'.__' \"\"'      `.,------'\"'      ,/            ,     `.._.' `.\n");
                System.out.print("  `.             | `--........,-'.            .         \\     \\\n");
                System.out.print("    `-.          .   '.,--\"\"     |           ,'\\        |      .\n");
                System.out.print("       `.       /     |          L          ,\\  .       |  .,---.\n");
                System.out.print("         `._   '      |           \\        /  .  L      | /   __ `.\n");
                System.out.print("            `-.       |            `._   ,    l   .    j |   '  `. .\n");
                System.out.print("              |       |               `\"' |  .    |   /  '      .' |\n");
                System.out.print("              |       |                   j  |    |  /  , `.__,'   |\n");
                System.out.print("              `.      L                 _.   `    j ,'-'           |\n");
                System.out.print("               |`\"---..\\._______,...,--' |   |   /|'      /        j\n");
                System.out.print("               '       |                 |   .  / |      '        /\n");
                System.out.print("                .      .              ____L   \\'  j    -',       /\n");
                System.out.print("               / `.     .          _,\"     \\   | /  ,-','      ,'\n");
                System.out.print("              /    `.  ,'`-._     /         \\  i'.,'_,'      .'\n");
                System.out.print("             .       `.      `-..'             |_,-'      _.'\n");
                System.out.print("             |         `._      |            ''/      _,-'\n");
                System.out.print("             |            '-..._\\             `__,.--'\n");
                System.out.print("            ,'           ,' `-.._`.            .\n");
                System.out.print("           `.    __      |       \"'`.          |\n");
                System.out.print("             `-\"'  `\"\"\"\"'            7         `.\n");
                System.out.print("                                    `---'--.,'\"`' mh\n");

                break;

            case "blastoise":
                System.out.print("                       _\n");
                System.out.print("            _,..-\"\"\"--' `,.-\".\n");
                System.out.print("          ,'      __.. --',  |\n");
                System.out.print("        _/   _.-\"' |    .' | |       ____\n");
                System.out.print("  ,.-\"\"'    `-\"+.._|     `.' | `-..,',--.`.\n");
                System.out.print(" |   ,.                      '    j 7    l \\__\n");
                System.out.print(" |.-'                            /| |    j||  .\n");
                System.out.print(" `.                   |         / L`.`\"\"','|\\  \\\n");
                System.out.print("   `.,----..._       ,'`\"'-.  ,'   \\ `\"\"'  | |  l\n");
                System.out.print("     Y        `-----'       v'    ,'`,.__..' |   .\n");
                System.out.print("      `.                   /     /   /     `.|   |\n");
                System.out.print("        `.                /     l   j       ,^.  |L\n");
                System.out.print("          `._            L       +. |._   .' \\|  | \\\n");
                System.out.print("            .`--...__,..-'\"\"'-._  l L  \"\"\"    |  |  \\\n");
                System.out.print("          .'  ,`-......L_       \\  \\ \\     _.'  ,'.  l\n");
                System.out.print("       ,-\"`. / ,-.---.'  `.      \\  L..--\"'  _.-^.|   l\n");
                System.out.print(" .-\"\".'\"`.  Y  `._'   '    `.     | | _,.--'\"     |   |\n");
                System.out.print("  `._'   |  |,-'|      l     `.   | |\"..          |   l\n");
                System.out.print("  ,'.    |  |`._'      |      `.  | |_,...---\"\"\"\"\"`    L\n");
                System.out.print(" /   |   j _|-' `.     L       | j ,|              |   |\n");
                System.out.print("`--,\"._,-+' /`---^..../._____,.L',' `.             |\\  |\n");
                System.out.print("   |,'      L                   |     `-.          | \\j\n");
                System.out.print("            .                    \\       `,        |  |\n");
                System.out.print("             \\                __`.Y._      -.     j   |\n");
                System.out.print("              \\           _.,'       `._     \\    |  j\n");
                System.out.print("              ,-\"`-----\"\"\"\"'           |`.    \\  7   |\n");
                System.out.print("             /  `.        '            |  \\    \\ /   |\n");
                System.out.print("            |     `      /             |   \\    Y    |\n");
                System.out.print("            |      \\    .             ,'    |   L_.-')\n");
                System.out.print("             L      `.  |            /      ]     _.-^._\n");
                System.out.print("              \\   ,'  `-7         ,-'      / |  ,'      `-._\n");
                System.out.print("             _,`._       `.   _,-'        ,',^.-            `.\n");
                System.out.print("          ,-'     v....  _.`\"',          _:'--....._______,.-'\n");
                System.out.print("        ._______./     /',,-'\"'`'--.  ,-'  `.\n");
                System.out.print("                 \"\"\"\"\"`.,'         _\\`----...' mh\n");
                System.out.print("                        --------\"\"'\n");
                System.out.print("\n");
                System.out.print("\n");

                break;

            case "snorlax":
                System.out.print("      ::                                              \n");
                System.out.print("      HHH:                   :HH                      \n");
                System.out.print("      HHHHH:               :HHHH                      \n");
                System.out.print("      HHHHHH: :HHHHHHHHH: :HHHHH                      \n");
                System.out.print("      HHHHHHHHHHHHHHHHHHH:HHHHHH                      \n");
                System.out.print("      :HHHHHHHHHHHHHHHHHHHHHHHHH                      \n");
                System.out.print("      ,HHHHHHHH:,,,,:HHHH:,,:HHH                      \n");
                System.out.print("       HHHHHH:,      ,:H:    ,:H                      \n");
                System.out.print("       HHHHH:,  :HH:  ,:  :H: ,:                      \n");
                System.out.print("      :HHHH:,,:H             :H,:                     \n");
                System.out.print("      HHHHH,,,,       :::       H                     \n");
                System.out.print("      HHHH:,,,,      :::::      :,                    \n");
                System.out.print("      HHHH,,,,,,    ,:::::,     ,:                    \n");
                System.out.print("     ,HHHH,,,,,,,   H::,,:H     ,H,                   \n");
                System.out.print("     :HHHH,,,,,,,,  H: ,, H    ,,HH:,:HHHH:,          \n");
                System.out.print("     H:::HHHH:,,,,,:HHHHHHHHHHHH:HHHHHHHHHHH:         \n");
                System.out.print("    ::HHHH:,:H:,:HH::,,         ,:HHH ,HHHHHH:        \n");
                System.out.print("   :HHHHHHHH:, HH::,,             ,:H :HHHHHHH:       \n");
                System.out.print("  :HHHHHHHHHHHHH:,,,               ,:HH:,, HHHH:      \n");
                System.out.print("  HHHHHHHHHHHH:, :,                  :H,,  HHHHH      \n");
                System.out.print(" ,HHHHHHHHHHHHH: H,                   :H  :HHHHH:     \n");
                System.out.print(" :HHHHHHHHHHHHHH:,                     :HHHHHHHHH     \n");
                System.out.print(" HHHHHHHHHHHHHH,,,                      :HHHHHHHH     \n");
                System.out.print(",HHHHHHHHHHHHH:,,,,                     ,:HHHHHH:     \n");
                System.out.print(":HHHHHHHHHHHH:,,,,,,                    ,,HHH: HHH:   \n");
                System.out.print("HHHHHHHHHHHH:,,,,,,:,                   ,,HHH, HH,H H:\n");
                System.out.print("HHHHHHHHHHHH,,:,,,H H,                 ,,:HH:,,:, H:,H\n");
                System.out.print("HHHHHHHHHHH:,: :,:   :,,H:            ,,,H::::H :H:, H\n");
                System.out.print("HHHHHHHHHHH,,H  HH,  H:H,H,,        ,,,,:H::,,     : :\n");
                System.out.print("HHHHHHHHHHH,:,  ::,, :H, H,,,,,,,,,,,,,,H::,,      ,: \n");
                System.out.print(":HHHHHHHHHHHH,,:,,:H:,:, :,,,,,,,,,,,,,:H:,,,       H \n");
                System.out.print(",HHHHHHHHHH:,:H,      ,:H,,,,,,,,,,,,,:H::,,        : \n");
                System.out.print(" HHHHHHHHHH,,,,         ,:,,,,,,,,:HHHHH:,,,   ,:,  ,:\n");
                System.out.print(" HHHHHHHHHH,,,           H,,,:HHHHHHHHHH:,,   ,:::,  H\n");
                System.out.print(" HHHHHHHHH:,,,   ,:::,   :::HHHHHHHHHHHH:,,   :::::  H\n");
                System.out.print(" HHHHHHHHH,,,    :::::,  ,HHHHHHHHHHHHHH:,,   :::::  H\n");
                System.out.print(" HHHHHHHHH,,,   ,::::::   HHHHHHHHHHHHHH:,,   ::::, ,:\n");
                System.out.print(" HHHHHHHHH,,,   :::::::   HHHHHHHHHHHHHH:,,   ,::,  : \n");
                System.out.print(" HHHHHHHHH,,,   :::::::   HHHHHHHHHHHHHH:,,    ,,   H \n");
                System.out.print(" :HHHHHHHH,,,   :::::::   HHHHHHHHHHHHHH:,,,       ,: \n");
                System.out.print(" ,HHHHHHHH,,,   ::::::,   HHHHHHHHHHHHHHH:,,      ,:  \n");
                System.out.print("  HHHHHHHH,,,   ,:::::   ,HHHHHHHHHHHHHHH:,,,,  ,,H   \n");
                System.out.print("  :HHHHHHH,,,    ,:::,   :HHHHHHHHHHHHHHHH:,,,,,H:    \n");
                System.out.print("   :HHHHHH:,,,    ,:,   ,HHHHHHHHHHHHHHHHHHHHHH:      \n");
                System.out.print("    :HHHHHH,,,          :HHHHHHHHHHHHHHHHHH:,         \n");
                System.out.print("     :HHHHH:,,,        ,HHHHHHHHH:,                   \n");
                System.out.print("      :HHHHH:,,,      ,:HHHHHH:,                      \n");
                System.out.print("        H:HHH:,,,    ,:HH:,                           \n");
                System.out.print("              :HHHHHH:\n");

                break;

            case "jigglypuff":
                System.out.print("   ,..__\n");
                System.out.print("  |  _  `--._                                  _.--\"\"\"`.\n");
                System.out.print("  |   |._    `-.        __________         _.-'    ,|' |\n");
                System.out.print("  |   |  `.     `-..--\"\"_.        `\"\"-..,-'      ,' |  |\n");
                System.out.print("  L   |    `.        ,-'                      _,'   |  |\n");
                System.out.print("   .  |     ,'     ,'            .           '.     |  |\n");
                System.out.print("   |  |   ,'      /               \\            `.   |  |\n");
                System.out.print("   |  . ,'      ,'                |              \\ /  j\n");
                System.out.print("   `   \"       ,                  '               `   /\n");
                System.out.print("    `,         |                ,'                  '+\n");
                System.out.print("    /          |             _,'                     `\n");
                System.out.print("   /     .-\"\"\"'L          ,-' \\  ,-'\"\"\"\"`-.           `\n");
                System.out.print("  j    ,' ,.+--.\\        '    ',' ,.,-\"--._`.          \\\n");
                System.out.print("  |   / .'  L    `.        _.'/ .'  |      \\ \\          .\n");
                System.out.print(" j   | | `--'     |`+-----'  . j`._,'       L |         |\n");
                System.out.print(" |   L .          | |        | |            | |         |\n");
                System.out.print(" |   `\\ \\        / j         | |            | |         |\n");
                System.out.print(" |     \\ `-.._,.- /           . `         .'  '         |\n");
                System.out.print(" l      `-..__,.-'             `.`-.....-' _.'          '\n");
                System.out.print(" '                               `-.....--'            j\n");
                System.out.print("  .                  -.....                            |\n");
                System.out.print("   L                  `---'                            '\n");
                System.out.print("    \\                                                 /\n");
                System.out.print("     ` \\                                        ,   ,'\n");
                System.out.print("      `.`.    |                        /      ,'   .\n");
                System.out.print("        . `._,                        |     ,'   .'\n");
                System.out.print("         `.                           `._.-'  ,-'\n");
                System.out.print("    _,-\"\"\"\"`-,                             _,'\"-.._\n");
                System.out.print("  ,'          `-.._                     ,-'        `.\n");
                System.out.print(" /             _,' `\"-..___     _,..--\"`.            `.\n");
                System.out.print("|         _,.-'            `\"\"\"'         `-._          \\\n");
                System.out.print("`-....---'                                   `-.._      |\n");
                System.out.print("                                                  `--...' mh\n");

                break;

        }
    }
}
